import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpeg',
      price: 40,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpeg',
      price: 80,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpeg',
      price: 40,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 18,
      description: 'A popular shirt',
    },
    {
      name: 'Gold Pants',
      slug: 'gold-pants',
      category: 'Pants',
      image: '/images/pants1.jpeg',
      price: 40,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 3,
      countInStock: 40,
      description: 'A popular pant',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpeg',
      price: 76,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 12,
      description: 'A popular pant',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpeg',
      price: 40,
      brand: 'Casely',
      rating: 2.5,
      numReviews: 3,
      countInStock: 10,
      description: 'A popular pant',
    },
  ],
};

export default data;
