import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>eCommerce shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold text-center mt-8">
        eCommerce Project Set-up done
      </h1>
    </div>
  );
}
